version: '3.7'

networks:
  api:
    driver: bridge

services:
 
    api:
      container_name: ${ENV_PREFIX}back-api
      build:
         context: ./WebApplication1
         dockerfile: Dockerfile
      ports:
        - "5005:5005"
      #environment:
      #  - ASPNETCORE_URLS=http://+:5005
      #  - ASPNETCORE_ENVIRONMENT=Development
      env_file:
        - ".env"
      networks:
        - api
      
    front:
      container_name: ${ENV_PREFIX}list-user-front
      build:
         context: ./docker-front
         dockerfile: Dockerfile
      ports:
        - "80:80"
      